project_id = "zmfugicftfwvuudensdo"

[functions.create-livekit-token]
verify_jwt = true

[functions.generate-streamer-invite-token]
verify_jwt = true

[functions.manage-livekit-room]
verify_jwt = true

[functions.process-ticket-payment]
verify_jwt = true

[functions.stripe-webhook-handler]
verify_jwt = false

[functions.create-stripe-express-account]
verify_jwt = true

[functions.scoreboard-operations]
verify_jwt = false

[functions.check-stripe-account-status]
verify_jwt = true

[functions.event]
verify_jwt = false

[functions.report-event]
verify_jwt = true

[functions.create-ad-session]
verify_jwt = true

[functions.process-ad-billing]
verify_jwt = true

[[edge_functions]]
function = "event"
pattern = "/event/**"