name: Deploy PublicStreamer

on:
  push:
    branches:
      - publicstreamer

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |

            # Navigate to the project directory
            cd apps/public-hunt

            # Pull the latest changes from the repository
            git checkout publicstreamer
            git pull origin publicstreamer

            # Gracefully stop the containers to allow proper shutdown
             
             bun run build:publicstreamer
