name: Deploy Doghunt

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: 145.79.0.52
          username: root
          key: "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACCULYZtjaheLW+/DylpR6USf+/etMblAoKG+bf6vu2HcQAAAKhPeeOeT3njngAAAAtzc2gtZWQyNTUxOQAAACCULYZtjaheLW+/DylpR6USf+/etMblAoKG+bf6vu2HcQAAAEBrRaHMlH7LkTAdocWVo00vqRj993sg+FdU8AXDL3buopQthm2NqF4tb78PKWlHpRJ/7960xuUCgob5t/q+7YdxAAAAHnBlcnNvbmFsLmFiZHVycmFobWFuQGdtYWlsLmNvbQECAwQFBgc="
          script: |

            # Navigate to the project directory
            cd apps/publicstreamer

            # Pull the latest changes from the repository
            git pull origin prod

            # Gracefully stop the containers to allow proper shutdown
             
             bun run build:vps
